# - include_role:
#     name: kube_secrets
#   vars:
#     secret_namespace: immich
#     secret_name: immich-secrets
#     secret_data: "{{ immich_secrets }}"
- include_role:
    name: kube_namespaces
  vars: 
    namespace: immich

- include_role:
    name: kube_pvcs
  vars:
    namespace: immich
    pvc_list:
      - pvc_name: immich-library
        storage: 1Ti
        storage_class: nfs-rwx
        multi_node_access: true
      - pvc_name: immich-postgres
        storage: 20Gi
        storage_class: nfs-rwo
        multi_node_access: false
      - pvc_name: machine-learning
        storage: 10Gi
        storage_class: nfs-rwx
        multi_node_access: true
  
    
- name: Add Immich Helm repo
  command: helm repo add immich https://immich-app.github.io/immich-charts

- name: Update Helm repos
  command: helm repo update

- name: Copy Immich values.yml from template directory
  template:
    src: values.yml
    dest: /tmp/immich-values.yml

- name: Copy Immich values.yaml from template directory
  template:
    src: immich-postgres.yml
    dest: /tmp/immich-postgres.yml


- name: Scale down Immich deployment to 0 replicas
  kubernetes.core.k8s_scale:
    api_version: apps/v1
    kind: Deployment
    namespace: immich
    name: immich
    replicas: 0
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  ignore_errors: yes

- name: Apply Immich Postgres statefulset manifest
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    src: /tmp/immich-postgres.yml

- name: Deploy Immich with Helm
  command: >
    helm upgrade --install immich immich/immich --namespace immich -f /tmp/immich-values.yml
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml

- name: Copy Immich VirtualService from template directory
  template:
    src: immich-vs.yml
    dest: /tmp/immich-vs.yml

- name: Apply Immich VirtualService
  delegate_to: control-plane
  become: true
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'immich-vs.yml') }}"

- name: Copy Immich VirtualService from template directory
  template:
    src: machine-vs.yml
    dest: /tmp/machine-vs.yml

- name: Apply Immich VirtualService
  delegate_to: control-plane
  become: true
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    definition: "{{ lookup('template', 'machine-vs.yml') }}"

- name: Wait for Immich pod to be ready
  command: /var/lib/rancher/rke2/bin/kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=immich-server -n immich --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
