---
- name: Create mount point and run script
  hosts: storage
  become: true
  gather_facts: false

  vars:
    script_path: "/tmp/myscript.sh"

  tasks:
    - name: Copy shell script to remote host
      ansible.builtin.copy:
        src: "./createmount.sh"
        dest: "{{ script_path }}"
        mode: "0755"

    - name: Run shell script
      ansible.builtin.command:
        cmd: "{{ script_path }}"
      register: script_result

    - name: Show script output
      ansible.builtin.debug:
        var: script_result.stdout_lines