---
- import_playbook: evaluate_ip.yml
- name: Unmount and clean up SMB share from Linux nodes
  hosts: all
  become: yes
  vars:
    fstype: "cifs"

  tasks:
    - name: Unmount the SMB share if mounted
      mount:
        path: "{{ mount_point }}/{{ item.mount_name }}"
        fstype: "{{ fstype }}"
        state: absent
      loop: "{{ smb_domains }}"

    - name: Remove fstab entry (if it exists)
      mount:
        path: "{{ mount_point }}/{{ item.mount_name }}"
        fstype: "{{ fstype }}"
        state: absent_from_fstab
      loop: "{{ smb_domains }}"
    
    - name: Unmount the nfs share if mounted
      mount:
        path: "{{ mount_point }}"
        fstype: "nfs"
        state: absent_from_fstab

    - name: Unmount the NFS share if mounted
      mount:
        path: "{{ mount_point }}"
        fstype: "nfs"
        state: absent

    
