---
- import_playbook: evaluate_ip.yml

- name: Force cleanup network mounts
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Lazy unmount SMB shares if stuck
      ansible.builtin.command:
        cmd: "umount -l {{ mount_point }}/{{ item.mount_name }}"
      loop: "{{ smb_domains | default([]) }}"
      failed_when: false
      changed_when: true

    - name: Lazy unmount NFS share if stuck
      ansible.builtin.command:
        cmd: "umount -l {{ mount_point }}"
      failed_when: false
      changed_when: true

    - name: Remove SMB shares from fstab
      ansible.posix.mount:
        path: "{{ mount_point }}/{{ item.mount_name }}"
        fstype: "cifs"
        state: absent_from_fstab
      loop: "{{ smb_domains | default([]) }}"

    - name: Remove NFS share from fstab
      ansible.posix.mount:
        path: "{{ mount_point }}"
        fstype: "nfs"
        state: absent_from_fstab