# This playbook will set the specified host to a static ip address
# utility for uniformity of the ip addresses

- name: Set static IP on Rocky Linux with dynamic interface detection
  hosts: localhost
  become: yes

  tasks:
    - name: Find active ethernet interface
      command: nmcli -t -f DEVICE,TYPE device status
      register: nmcli_output

    - name: Parse ethernet interface name
      set_fact:
        eth_iface: "{{ item.split(':')[0] }}"
      loop: "{{ nmcli_output.stdout_lines }}"
      when: "'ethernet' in item"
      register: iface_fact



    - name: Debug parsed ethernet interfaces
      debug:
        var: iface_fact.results

    - name: Set interface fact from first ethernet device found
      set_fact:
        eth_iface: "{{ iface_fact.results | selectattr('skipped', 'equalto', False) | map(attribute='ansible_facts.eth_iface') | first }}"
      when: eth_iface is not defined

    - name: Debug selected interface
      debug:
        var: eth_iface

    - name: Configure static IP using nmcli (manual method)
      command: >
        nmcli con mod "{{ eth_iface }}" ipv4.method auto
        ipv4.addresses ""
        ipv4.gateway ""
        ipv4.dns ""

    - name: Update NetworkManager connections
      command: nmcli con up "{{ eth_iface }}"

    - name: Wait for network to stabilize
      pause:
        seconds: 10

    - name: Confirm interface IP
      command: ip -4 addr show dev "{{ eth_iface }}"
      register: ip_check

    - name: Display assigned IP
      debug:
        var: ip_check.stdout_lines
