---

- name: Bootstrap control node
  hosts: localhost
  gather_facts: false
  roles:
    - role: bootstrap_collections
      when: state == 'present'
    
- import_playbook: evaluate_ip.yml
  tags:
    - active

- import_playbook: install_helm.yml
  tags:
    - active

- name: "{{ state }}ing RKE2 nodes "
  hosts: ClusterGroup
  become: true
  gather_facts: false
  roles:
    - role: rke2


- name: Deploy MetalLB 
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: metallb
      when: state == 'present'
      tags:
        - metallb
        
- import_playbook: deploy_storage.yml
  tags:
    - nfs
  when: state == 'present'

- name: Deploy Argo CD
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: argocd
      when: state == 'present'
      tags:
        - argocd

- name: Deploy Certmanager
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: cert_manager
      when: state == 'present'
      tags:
        - certs

# - name: Deploy Istio
#   hosts: control
#   gather_facts: false
#   become: true
#   roles:
#     - role: istio
#       when: state == 'present'
#       tags:
#         - istio


# - name: Deploy NFS Provisioner
#   hosts: control
#   gather_facts: false
#   become: true
#   roles:
#     - role: nfs-provisioner
#       when: state == 'present'
#       tags:
#         - nfs



# # - name: Deploy SMB Shares to Storage Node
# #   hosts: ClusterGroup
# #   gather_facts: false
# #   become: true
# #   roles:
# #     - role: smb_fileshares
# #       when: state == 'present'
# #       tags:
# #         - smb


- name: Deploy Rancher 
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: rancher
      when: state == 'present'
      tags:
        - rancher

# - name: Deploy Rancher 
#   hosts: control
#   gather_facts: false
#   become: true
#   roles:
#     - role: nextcloud
#       when: state == 'present'
#       tags:
#         - rancher

# - name: Deploy Rancher 
#   hosts: control
#   gather_facts: false
#   become: true
#   roles:
#     - role: immich
#       when: state == 'present'
#       tags:
#         - rancher
