---

- name: Bootstrap control node
  hosts: localhost
  gather_facts: false
  roles:
    - role: bootstrap_collections
      when: state == 'present'
    
- import_playbook: evaluate_ip.yml
  tags:
    - active

- name: "{{ state }}ing RKE2 nodes "
  hosts: ClusterGroup
  become: true
  gather_facts: false
  roles:
    - role: rke2


- name: Deploy MetalLB 
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: metallb
      when: state == 'present'
      tags:
        - metallb

- name: Deploy NFS Provisioner
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: nfs-provisioner
      when: state == 'present'
      tags:
        - nfs

- import_playbook: deploy_storage.yml
  tags:
    - nfs
  when: state == 'present'

- import_playbook: configure_fileshares.yml
  tags:
    - nfs
  when: state == 'present'


- import_playbook: remove_fileshares.yml
  tags:
    - nfs
  when: state == 'absent'

- name: Deploy Istio
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: istio
      when: state == 'present'
      tags:
        - istio

- name: Deploy Certmanager
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: cert_manager
      when: state == 'present'
      tags:
        - certs

- name: Deploy Rancher 
  hosts: control
  gather_facts: false
  become: true
  roles:
    - role: rancher
      when: state == 'present'
      tags:
        - rancher
