---

- name: Bootstrap control node
  hosts: localhost
  gather_facts: false
  roles:
    - role: bootstrap_collections
      when: state == 'present'
    
- import_playbook: evaluate_ip.yml
  tags:
    - active

- name: "{{ state }}ing RKE2 nodes "
  hosts: ClusterGroup
  become: true
  roles:
    - role: rke2


- name: Deploy MetalLB 
  hosts: control
  become: true
  roles:
    - role: metallb
      when: state == 'present'
      tags:
        - metallb
