---
- name: Delete ALL Kubernetes secrets in the cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get all secrets across all namespaces
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
      register: secrets

    - name: Delete each secret
      kubernetes.core.k8s:
        state: absent
        definition: "{{ item }}"
      loop: "{{ secrets.resources }}"
