---
# Put values on manager node for quick testing and rollingforward strats
- name: Copy ClusterIssuer template to remote source
  template:
    src: clusterissuer.yml.j2
    dest: /tmp/clusterissuer.yml

- name: Apply ClusterIssuer template
  delegate_to: control-plane
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'clusterissuer.yml.j2') }}"