all:
  hosts:
    dev:
      ansible_host: 59.22.6.128
      internal_address:
        ip: 59.22.60.200
        gateway: 59.22.0.1
        dns: 59.22.0.1
      external_address:
        ip: 192.168.0.200
        gateway: 192.168.0.1
        dns: 192.168.0.1
  vars:
    netmask: 16

ClusterGroup:
  children:
    develop:
    
develop:
  hosts:
    dev:

