all:
  hosts:
    control-plane:
      ansible_host: 59.22.6.134
      internal_address:
        ip: 59.22.6.100
        gateway: 59.22.0.1
        dns: 59.22.0.1
      external_address:
        ip: 192.168.0.100
        gateway: 192.168.0.1
        dns: 192.168.0.1
    worker1:
      ansible_host: 59.22.6.130
      internal_address:
        ip: 59.22.6.101
        gateway: 59.22.0.1
        dns: 59.22.0.1
      external_address:
        ip: 192.168.0.101
        gateway: 192.168.0.1
        dns: 192.168.0.1
    worker2:
      ansible_host: 59.22.6.131
      internal_address:
        ip: 59.22.6.102
        gateway: 59.22.0.1
        dns: 59.22.0.1
      external_address:
        ip: 192.168.0.102
        gateway: 192.168.0.1
        dns: 192.168.0.1
    worker3:
      ansible_host: 59.22.6.132
      internal_address:
        ip: 59.22.6.103
        gateway: 59.22.0.1
        dns: 59.22.0.1
      external_address:
        ip: 192.168.0.103
        gateway: 192.168.0.1
        dns: 192.168.0.1

  vars:
    netmask: 24
    storage_node: worker1
    storage_node_ip: 192.168.0.101
    samba_assigned_ip: 192.168.0.235
    nfs_assigned_ip: 192.168.0.236

ClusterGroup:
  children:
    control:
    workers:

control:
  hosts:
    control-plane:

workers:
  hosts:
    worker[1:3]:
