all:
  hosts:
    manager:
      ansible_host: 10.22.6.110
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.100
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.100
        gateway: 192.168.0.1
        dns: 192.168.0.1

    lunap:
      ansible_host: 192.168.0.144
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.98
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.98
        gateway: 192.168.0.1
        dns: 192.168.0.1

    diana:
      ansible_host: 192.168.0.29
      ansible_user: rocky9
      external_address:
        ip: 192.168.0.99
        gateway: 192.168.0.1
        dns: 192.168.0.1
    
    d1:
      ansible_host: 192.168.0.30
      ansible_user: rocky9
      external_address:
        ip: 192.168.0.108
        gateway: 192.168.0.1
        dns: 192.168.0.1

    g1:
      ansible_host: 10.22.6.111
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.101
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.101
        gateway: 192.168.0.1
        dns: 192.168.0.1

    g2:
      ansible_host: 10.22.6.113
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.105
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.105
        gateway: 192.168.0.1
        dns: 192.168.0.1

    g3:
      ansible_host: 10.22.6.114
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.112
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.112
        gateway: 192.168.0.1
        dns: 192.168.0.1

    g4:
      ansible_host: 10.22.6.115
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.104
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.104
        gateway: 192.168.0.1
        dns: 192.168.0.1
    l1:
      ansible_host: 192.168.0.176
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.106
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.106
        gateway: 192.168.0.1
        dns: 192.168.0.1
    l2:
      ansible_host: 192.168.0.50
      ansible_user: rocky9
      internal_address:
        ip: 10.22.6.107
        gateway: 10.22.6.1
        dns: 10.22.6.1
      external_address:
        ip: 192.168.0.107
        gateway: 192.168.0.1
        dns: 192.168.0.1
  vars:
    netmask: 16
    storage_node: l1
    storage_node_ip: 192.168.0.106
    samba_assigned_ip: 192.168.0.235
    nfs_assigned_ip: 192.168.0.236
    kube_vip_address: 192.168.0.237

ClusterGroup:
  children:
    control:
    workers:

control:
  hosts:
    manager:
    lunap:
    diana:

workers:
  hosts:
    g[1:4]:
    l[1:2]:
    d1:

storage:
  hosts:
    l1: