all:
  hosts:
    control-plane:
      ansible_host: 192.168.1.101
      static_ip: 192.168.1.101
    worker1:
      ansible_host: 192.168.1.102
      static_ip: 192.168.1.102


Galaxia:
  children:
    control:
    workers:
    
control:
  hosts:
    control-plane:

workers:
  hosts:
    worker1: