ansible_become_pass: "{{ ansible_ssh_pass }}"
ansible_user: rocky9
kubeconfig: /etc/rancher/rke2/rke2.yaml
kube_env:
  KUBECONFIG: /etc/rancher/rke2/rke2.yaml

cert_dir: "{{ mount_point }}/certs"
rke_ports:
  - port: 53
    protocol: tcp 
  - port: 53
    protocol: udp
  - port: 9345    # RKE2 supervisor
    protocol: tcp 
  - port: 6443    # Kube API
    protocol: tcp 
  - port: 10250   # Kubelet
    protocol: tcp 
  - port: 8472    # Flannel VXLAN
    protocol: udp  
  - port: 2379    # etcd (control plane only)
    protocol: tcp   
  - port: 2380    # desc: "etcd peer" }
    protocol: tcp 
  - port: 10256   # desc: "kube-proxy health check" }
    protocol: tcp 
  - port: 53      # dsc: "DNS (CoreDNS)" }  
    protocol: udp 
  - port: 53      # desc: "DNS (CoreDNS)" }
    protocol: tcp 

# The node that owns the USB/external hard drive
storage_host_path: /mnt/windows/share/
next_cloud_storage_path: "{{ storage_host_path }}/nextcloud-data"

# SMB user bootstrap (optional)
smb_user: eriq
smb_pass: "changeme"   # leave empty ("") if you want to skip

tls_servers:
  - port:
      number: 443
      name: https-galaxia
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: galaxia-tls
    hosts:
      - "*.chaoscauldron.space"
      - "chaoscauldron.space"
  - port:
      number: 80
      name: http-galaxia
      protocol: HTTP
    hosts:
      - "*.chaoscauldron.space"
      - "chaoscauldron.space"
    tls:
      httpsRedirect: false