- name: Close required firewall ports
  ansible.builtin.shell: >
    firewall-cmd --permanent --zone=public
    {% for item in firewall_ports %}
    --remove-port={{ item.port }}/{{ item.protocol }}
    {% endfor %}
    && firewall-cmd --reload