- name: Open required firewall ports
  ansible.builtin.shell: >
    firewall-cmd --permanent
    {% for item in firewall_ports %}
    --add-port={{ item.port }}/{{ item.protocol }}
    {% endfor %}
    && firewall-cmd --reload